# metricbeat.config.modules:
#   path: ${path.config}/modules.d/*.yml
#   reload.enabled: false

metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - uptime
      - socket_summary
      - core
      - diskio
      - filesystem
      - fsstat
      - socket

    enabled: true
    period: 10s
    processes: [".*"]

output.elasticsearch:
  hosts: "${ELASTICSEARCH_HOSTS}"
  # username: "${ELASTICSEARCH_USERNAME}"
  # password: "${ELASTICSEARCH_PASSWORD}"
  index: "metricbeat-elasticserver-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.kibana:
  host: "${KIBANA_HOST}"
  # username: ${ELASTICSEARCH_USERNAME}
  # password: ${ELASTICSEARCH_PASSWORD}

setup.dashboards.enabled: true

setup.template.name: "metricbeat-elasticserver"
setup.template.pattern: "metricbeat-elasticserver-*"
setup.template.overwrite: true
# setup.template.settings:
#   index.number_of_shards: 1

monitoring.enabled: true

setup.ilm:
  enabled: true
  rollover_alias: "metricbeat-elasticserver"
  pattern: "{now/d}-000001"
  policy_file: "ilm.json"
